name: upload demo

on:
  workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Install
            env:
              APP_ENV: Demo
              DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            run: echo "environment $APP_ENV and $DB_PASSWORD"
          - name: upload file
            run: |
              echo "hello hamza form ci/cd pipeline" > demo.txt
              echo "file created successfully"
          
          - name: upload
            uses: actions/upload-artifact@v7
            with:
              name: upload-artifact
              path: .
    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
          - name: test job
            run: echo "my tst job"
            
            
          
            
        
              
             